source "https://rubygems.org"

gem "jekyll", "~> 4.3.4"

group :jekyll_plugins do
  gem 'jekyll-seo-tag', '~> 2.8'
  gem 'jekyll-last-modified-at', '~> 1.3', '>= 1.3.2'
  gem 'jekyll-minifier', '~> 0.1.10'
  gem 'jekyll_picture_tag', '~> 2.1', '>= 2.1.2'
end


platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", ">= 1", "< 3"
  gem "tzinfo-data"
end

gem "wdm", "~> 0.1", :platforms => [:mingw, :x64_mingw, :mswin]
gem "http_parser.rb", "~> 0.6.0", :platforms => [:jruby]
